import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#fbf9f6",
        "surface-dim": "#dbdad7",
        "surface-bright": "#fbf9f6",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f5f3f1",
        "surface-container": "#efeeeb",
        "surface-container-high": "#e9e8e5",
        "surface-container-highest": "#e3e2e0",
        "on-surface": "#1b1c1a",
        "on-surface-variant": "#434843",
        "inverse-surface": "#30312f",
        "inverse-on-surface": "#f2f0ee",
        outline: "#737873",
        "outline-variant": "#c3c8c1",
        "surface-tint": "#4e6354",
        primary: "#465b4c",
        "on-primary": "#ffffff",
        "primary-container": "#5e7464",
        "on-primary-container": "#e1f9e5",
        "inverse-primary": "#b5ccba",
        secondary: "#4c6454",
        "on-secondary": "#ffffff",
        "secondary-container": "#cce6d2",
        "on-secondary-container": "#516858",
        tertiary: "#6e4e51",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#886669",
        "on-tertiary-container": "#ffefef",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d0e9d5",
        "primary-fixed-dim": "#b5ccba",
        "on-primary-fixed": "#0b1f14",
        "on-primary-fixed-variant": "#374b3d",
        "secondary-fixed": "#cfe9d5",
        "secondary-fixed-dim": "#b3cdba",
        "on-secondary-fixed": "#092014",
        "on-secondary-fixed-variant": "#354c3d",
        "tertiary-fixed": "#ffd9dc",
        "tertiary-fixed-dim": "#e6bcbf",
        "on-tertiary-fixed": "#2c1518",
        "on-tertiary-fixed-variant": "#5d3f42",
        background: "#fbf9f6",
        "on-background": "#1b1c1a",
        "surface-variant": "#e3e2e0",
        accent: "#3B82F6",
      },
      fontFamily: {
        manrope: ["Manrope", "sans-serif"],
        inter: ["Inter", "sans-serif"],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        card: "0 4px 24px rgba(70,91,76,0.08)",
        "card-hover": "0 8px 32px rgba(70,91,76,0.14)",
        primary: "0 8px 24px rgba(70,91,76,0.25)",
        error: "0 8px 20px rgba(186,26,26,0.25)",
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        "float-delay-1": "float 5s ease-in-out 1s infinite",
        "float-delay-2": "float 7s ease-in-out 2s infinite",
        "float-delay-3": "float 6s ease-in-out 3s infinite",
        "fade-in": "fadeIn 0.5s ease-out",
        "slide-up": "slideUp 0.5s ease-out",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-12px)" },
        },
        fadeIn: {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        slideUp: {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
